# Generated by Django 3.2.7 on 2021-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmindetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
